version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: inventarysystem_db
    restart: always
    environment:
      POSTGRES_USER: admin_saas
      POSTGRES_PASSWORD: supersecretpassword
      POSTGRES_DB: InventarySystemDB
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: